call/urls.py
from django.urls import path
from . import views

app_name = "calls"

urlpatterns = [
    path('<username>/video/', views.videoCall, name='videoCall'),
    path('get_token/', views.getToken),
    
    path('<username>/video/create_member/', views.createMember),
    path('video/get_member/', views.getMember),
    path('video/delete_member/', views.deleteMember),
]

facebook/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    
    path("user/", include("userauths.urls")),
    path("comment/", include("comments.urls")),
    path("friend/", include("friends.urls")),
    path("inbox/", include("chat.urls")),
    path("call/", include("call.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path 
from userauths import views 
from django.contrib.auth import views as auth_views

app_name = "userauths"

urlpatterns = [
    path("register/", views.RegisterView, name="register"),
    path("login/", views.LoginView, name="login"),
    path("logout/", views.LogoutView, name="logout"),
    
    path("my-profile/", views.my_profile, name="my-profile"),
    path("profile/<username>/", views.friend_profile, name="profile"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("search/", views.search_users, name="search_users"),
    
    # Change password
    path("change-password/", auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',
                                               success_url = '/user/password-reset-complete/'), name="change_password"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), 
                                                    name='password_reset_complete'),
]

templates/partials/settings_sidebar.html
<div class="lg:w-1/3">
  <nav class="responsive-nav setting-nav setting-menu" uk-sticky="top:30 ; offset:80 ; media:@m ;bottom:true; animation: uk-animation-slide-top">
    <h4 class="mb-0 p-3 uk-visible@m hidden">Setting Navigation</h4>
    <ul>
      <li class="{% if request.path == '/user/profile-update/' %}{% endif %}">
        <a href="{% url 'userauths:profile-update' %}"><i class="uil-cog"></i> Tổng quan</a>
      </li>
      <li class="{% if request.path == '/user/change-password/' or request.path == '/user/password-reset-complete/' %}{% endif %}">
        <a href="{% url 'userauths:change_password'%}"><i class="uil-unlock-alt"></i> Mật khẩu</a>
      </li>
    </ul>
  </nav>
</div>