call/urls.py
from django.urls import path
from . import views

app_name = "calls"

urlpatterns = [
    path('<username>/video/', views.videoCall, name='videoCall'),
    path('get_token/', views.getToken),
    
    path('<username>/video/create_member/', views.createMember),
    path('video/get_member/', views.getMember),
    path('video/delete_member/', views.deleteMember),
]

facebook/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    
    path("user/", include("userauths.urls")),
    path("comment/", include("comments.urls")),
    path("friend/", include("friends.urls")),
    path("inbox/", include("chat.urls")),
    path("call/", include("call.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path 
from userauths import views 
from django.contrib.auth import views as auth_views

app_name = "userauths"

urlpatterns = [
    path("register/", views.RegisterView, name="register"),
    path("login/", views.LoginView, name="login"),
    path("logout/", views.LogoutView, name="logout"),
    
    path("my-profile/", views.my_profile, name="my-profile"),
    path("profile/<username>/", views.friend_profile, name="profile"),
    path("profile-update/", views.profile_update, name="profile-update"),
    path("search/", views.search_users, name="search_users"),
    
    # Change password
    path("change-password/", auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',
                                               success_url = '/user/password-reset-complete/'), name="change_password"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), 
                                                    name='password_reset_complete'),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.utils.html import mark_safe
from shortuuid.django_fields import ShortUUIDField
from cloudinary.models import CloudinaryField
import cloudinary.uploader
import re
from django.dispatch import receiver

# Create your models here.

RELATIONSHIP = (
    ('single', 'Single'),
    ('married', 'Married'),
    ('inrelationship', 'In Relationship'),
)

GENDER = (
    ("female", "Female"),
    ("male", "Male"),
)

WHO_CAN_SEE_MY_FRIENDS  = (
    ('Everyone', 'Everyone'),
    ('Friends', 'Friends'),
    ('Only Me', 'Only Me'),
)

class User(AbstractUser):
    full_name = models.CharField(max_length=255, null=True, blank=True)
    username = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    gender = models.CharField(max_length=50, choices=GENDER)
    
    otp = models.CharField(max_length=100, blank=True, null=True)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]
    
    def __str__(self):
        return str(self.username)
    
    
    
class Profile(models.Model):
    pid = ShortUUIDField(length=7, max_length=25, alphabet="abcdefghijklmnopqrstuvxyz123")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cover_image = CloudinaryField('cover_image', blank=True, null=True, default="https://res.cloudinary.com/ddfsqd1ru/image/upload/v1716366005/media/cover_x5yc8e.jpg")
    image = CloudinaryField('image', blank=True, null=True, default="https://res.cloudinary.com/ddfsqd1ru/image/upload/v1716366005/media/default_lelg4l.jpg")
    full_name = models.CharField(max_length=255, blank=True, null=True)
    bio = models.CharField(max_length=100, blank=True, null=True)
    about_me = models.CharField(max_length=255, blank=True, null=True) 
    phone = models.CharField(max_length=50, blank=True, null=True)
    gender = models.CharField(max_length=50, choices=GENDER, null=True)
    relationship = models.CharField(max_length=50, choices=RELATIONSHIP, null=True)
    friends_visibility = models.CharField(max_length=50, choices=WHO_CAN_SEE_MY_FRIENDS, null=True, default='Everyone')
    country = models.CharField(max_length=255, blank=True, null=True)  
    city = models.CharField(max_length=255, blank=True, null=True)
    state = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    working_at = models.CharField(max_length=255, blank=True, null=True)
    instagram = models.URLField(default='https://instagram.com/', blank=True, null=True)
    verified = models.BooleanField(default=False)
    followers = models.ManyToManyField(User, related_name='followers', blank=True)
    following = models.ManyToManyField(User, related_name='following', blank=True)
    friends = models.ManyToManyField(User, related_name='friends', blank=True)
    blocked = models.ManyToManyField(User, related_name='blocked', blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    
        
    
    class Meta:
        ordering = ['-date']
        
    def __str__(self):
        if self.full_name:
            return str(self.full_name)
        else:
            return str(self.user.username)
        
    def thumbnail(self):
        return mark_safe('<img src="%s" width="50" height="50" object-fit:"cover" style="border-radius: 30px;" />' % (self.image.url))
    

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)
    

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ImageField, FileInput, TextInput, Select

from userauths.models import Profile, User

class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'id': "", 'placeholder':'Họ tên'}), 
                                max_length=100, required=True,error_messages={'required' : 'Vui lòng nhập họ tên'})
    username = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'id': "", 'placeholder':'Tài khoản'}), 
                               max_length=100, required=True,error_messages={'required' : 'Vui lòng nhập tài khoản'})
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': '', 'id': "", 'placeholder':'SĐT'}), 
                            max_length=100, required=True,error_messages={'required' : 'Vui lòng nhập số điện thoại'})
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': '' , 'id': "", 'placeholder':'Email'}), 
                             required=True,error_messages={'required' : 'Vui lòng nhập Email'})
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'id': "", 'placeholder':'Mật khẩu'}), 
                                required=True,error_messages={'required' : 'Vui lòng nhập mật khẩu'})
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'id': "", 'placeholder':'Xác nhận mật khẩu'}), 
                                required=True,error_messages={'required' : 'Vui lòng nhập xác nhận mật khẩu'})
    # gender = forms.CharField(widget=forms.TextInput(attrs={ 'class': 'with-border' , 'id': "", 'placeholder':'Enter Gender'}))
    
    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'password1', 'password2', 'phone', 'gender']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'with-border'
            # visible.field.widget.attrs['placeholder'] = visible.field.label


class ProfileUpdateForm(forms.ModelForm):
    image = ImageField(widget=FileInput)
    
    class Meta:
        model = Profile
        fields = [
            'cover_image' ,
            'image' ,
            'full_name', 
            'bio', 
            'about_me', 
            'phone',
            'gender',
            'relationship',
            'friends_visibility',
            'country', 
            'city', 
            'state', 
            'address', 
            'working_at',
            'instagram',
        ]

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from userauths.forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm

from userauths.models import User, Profile
from posts.models import Post
from friends.models import FriendRequest

# Create your views here.

def RegisterView(request, *args, **kwargs):
    if request.user.is_authenticated:
        messages.warning(request, f"Người dùng {request.user.username} đã đăng nhập ")
        return redirect('posts:feed')
    
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        full_name = form.cleaned_data.get('full_name')
        phone = form.cleaned_data.get('phone')
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password1')
        
        user = authenticate(email=email, password=password)
        login(request, user)
        
        messages.success(request, f"Xin chào {request.user.username}, tài khoản của bạn đã đươc tạo thành công.")
        
        profile = Profile.objects.get(user=request.user)
        profile.full_name = full_name
        profile.phone = phone
        profile.save()
        
        return redirect('posts:feed')
    
    context = {'form': form}
    
    return render(request, 'userauths/register.html', context)


def LoginView(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        if email:
            try:
                user = User.objects.get(email=email)
                user = authenticate(request, email=email, password=password)
                if user is not None :
                    login(request, user)
                    # messages.success(request, "Đăng nhập thành công")
                    return redirect('posts:feed')
                else :
                    messages.error(request, "Email hoặc mật khẩu không đúng")
            except:
                messages.error(request, "Người dùng không tồn tại")
    return HttpResponseRedirect("/")

def LogoutView(request):
    logout(request)
    messages.success(request, 'Đăng xuất thành công')
    return redirect("userauths:register")


@login_required
def my_profile(request):
    profile = request.user.profile
    posts = Post.objects.filter(user=request.user, active = True)
    # groups = Group.objects.filter(active=True, user=request.user)
    
    context = {
        'posts': posts,
        'profile': profile,
        # 'groups': groups,
    }
    
    return render(request, 'userauths/my-profile.html', context)


@login_required
def friend_profile(request, username):
    profile = Profile.objects.get(user__username=username)
    posts = Post.objects.filter(active=True, user=profile.user)

    # Send Friend Request Feature
    bool = False
    bool_friend = False

    sender = request.user
    receiver = profile.user
    bool_friend = False
    print("========================  Thêm hoặc hủy")
    try:
        friend_request = FriendRequest.objects.get(sender=sender, receiver=receiver)
        if friend_request:
            bool = True
        else:
            bool = False
    except:
        bool = False
    # if receiver not in sender.profile.friends.all():
    #     pass
    # else:
    #     print("========================  Unfriend")
    #     bool_friend = False

    # End Send Friend Request Feature
    print("Bool =======================", bool)
    

    context = {
        "posts":posts,
        "bool_friend":bool_friend,
        "bool":bool,
        "profile":profile,
    }
    return render(request, "userauths/friend-profile.html", context)


@login_required
def profile_update(request):
    if  request.method == "POST":
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile) 
        u_form = UserUpdateForm(request.POST, instance=request.user)
        print(request.POST)

        if p_form.is_valid() and u_form.is_valid():
            p_form.save()
            u_form.save()
            messages.success(request, 'Hồ sơ đã cập nhật thành công')
            return redirect('userauths:profile-update')
    else:
        p_form = ProfileUpdateForm(instance=request.user.profile)
        u_form = UserUpdateForm(instance=request.user)
        
    
    context = {
        'p_form': p_form,
        'u_form': u_form,
    }
    
    return render(request, 'userauths/profile-update.html', context)

def search_users(request):
    query = request.GET.get('q')
    if query:
        users = User.objects.filter(username__icontains=query) | User.objects.filter(email__icontains=query) | User.objects.filter(full_name__icontains=query)

        users_data = []
        for user in users:
            try:
                profile = Profile.objects.get(user=user)
                profile_image = profile.image.url
                full_name = profile.full_name
            except Profile.DoesNotExist:
                profile_image = None
                full_name = None

            user_data = {
                'username': user.username,
                'full_name': full_name,
                'email': user.email,
                'profile_image': profile_image,
            }
            users_data.append(user_data)
    else:
        users_data = []
    return JsonResponse({'users': users_data})
        

templates/userauths/profile-update.html
{% extends 'partials/base.html' %} 
{% load static %}
{% load widget_tweaks %} 
{% block content %}

<style>
  #id_image {
    background-color: #270041;
    border-radius: 4px;
    height: 50px;
    width: 100%;
    color: #ffffff;
  }
  #id_image::file-selector-button {
    border: none;
    border-radius: 7px;
    color: 432f9f;
    background-color: #ffffff;
    height: 30px;
    cursor: pointer;
    transition: all 0.25s ease-in;
    margin-top: 1px;
    margin-left: 10px;
  }
</style>

<!-- Main Contents -->
<div class="main_content">
  <div class="mcontainer">
    <div
      class="bg-white lg:divide-x lg:flex lg:shadow-md rounded-md shadow lg:rounded-xl overflow-hidden lg:m-0 -mx-4"
    >
      {% include 'partials/settings_sidebar.html' %}
      <div class="lg:w-2/3">
        <form
          method="POST"
          class="lg:flex lg:flex-col justify-between lg:h-full"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <!-- form header -->
          <div class="lg:px-10 lg:py-8 p-6">
            <h3 class="font-bold mb-2 text-xl">Hồ sơ</h3>
            <p class="">
              Thông tin này sẽ được hiển thị công khai vì vậy hãy cẩn thận với
              những gì bạn chia sẻ.
            </p>
          </div>

          <!-- form body -->
          <div class="lg:py-8 lg:px-20 flex-1 space-y-4 p-6">
            <h4><b>Cá nhân</b></h4>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
              <!-- Column 1: Profile Image -->
              <div
                class="bg-gray-100 p-4 flex items-center"
                style="border-radius: 10px"
              >
                <div class="relative">
                  <img
                    src="{{request.user.profile.image.url}}"
                    id="preview_avatar"
                    alt="Profile Picture"
                    class="w-24 h-24 rounded-full"
                  />
                  <label
                    for="id_image"
                    class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer"
                  >
                    <i class="fas fa-pen text-blue-500"></i>
                  </label>
                </div>
              </div>

              <!-- Column 2: Cover Image -->
              <div class="bg-blue-100 p-4" style="border-radius: 10px">
                <div class="relative">
                  <img
                    src="{{request.user.profile.cover_image.url}}"
                    id="preview_cover"
                    alt="Cover Image"
                    class="w-full h-32 object-cover rounded-lg"
                  />
                  <label
                    for="id_cover_image"
                    class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer"
                  >
                    <i class="fas fa-pen text-blue-500"></i>
                  </label>
                </div>
              </div>

              <script>
                var loadFile = function (event) {
                  var output = document.getElementById("preview_avatar");
                  output.src = URL.createObjectURL(event.target.files[0]);
                  output.onload = function () {
                    URL.revokeObjectURL(output.src); // free memory
                  };
                };

                var loadFile2 = function (event) {
                  var output2 = document.getElementById("preview_cover");
                  output2.src = URL.createObjectURL(event.target.files[0]);
                  output2.onload = function () {
                    URL.revokeObjectURL(output2.src); // free memory
                  };
                };
              </script>
            </div>
            <div class="d-none">
              <div class="line">
                {% render_field p_form.image onchange="loadFile(event)" class="hidden" %}
              </div>
              <div class="line">
                {% render_field p_form.cover_image onchange="loadFile2(event)" class="hidden" %}
              </div>
            </div>
            <div class="line">
              {% render_field p_form.full_name class="line__input" %}
              <span for="username" class="line__placeholder"> Họ tên </span>
            </div>
            <div class="line">
              {% render_field p_form.bio class="line__input" %}
              <span for="username" class="line__placeholder"> Bio </span>
            </div>
            <div class="line">
              {% render_field p_form.about_me class="line__input" %}
              <span for="username" class="line__placeholder"> Giới thiệu </span>
            </div>
            <div class="line">
              {% render_field p_form.gender class="line__input" %}
              <span for="username" class="line__placeholder"> Giới tính </span>
            </div>
            <div class="line">
              {% render_field p_form.relationship class="line__input" %}
              <span for="username" class="line__placeholder">
                Tình trạng hôn nhân
              </span>
            </div>
            <div class="line">
              {% render_field p_form.working_at class="line__input" %}
              <span for="username" class="line__placeholder">
                Làm việc tại
              </span>
            </div>
            <div class="line">
              {% render_field p_form.friends_visibility class="line__input" %}
              <span for="username" class="line__placeholder">
                Ai có thể thấy bạn tôi
              </span>
            </div>
          </div>

          <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
            <h4><b>Liên lạc</b></h4>
            <div class="line">
              {% render_field p_form.phone class="line__input" %}
              <span for="username" class="line__placeholder">
                Số điện thoại
              </span>
            </div>
            <div class="line">
              {% render_field u_form.email class="line__input" %}
              <span for="username" class="line__placeholder"> Email </span>
            </div>
            <div class="line">
              {% render_field u_form.username class="line__input" %}
              <span for="username" class="line__placeholder"> Username </span>
            </div>
          </div>

          <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
            <h4><b>Địa chỉ</b></h4>
            <div class="line">
              {% render_field p_form.address class="line__input" %}
              <span for="username" class="line__placeholder"> Địa chỉ </span>
            </div>
            <div class="line">
              {% render_field p_form.city class="line__input" %}
              <span for="username" class="line__placeholder"> Thành phố </span>
            </div>
            <div class="line">
              {% render_field p_form.state class="line__input" %}
              <span for="username" class="line__placeholder"> State </span>
            </div>
            <div class="line">
              {% render_field p_form.country class="line__input" %}
              <span for="username" class="line__placeholder"> Đất nước </span>
            </div>
          </div>

          <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
            <h4><b>Socila URLs</b></h4>
            <div class="line">
              {% render_field p_form.instagram class="line__input" %}
              <span for="username" class="line__placeholder"> Instagram </span>
            </div>
          </div>

          <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">
            <button type="submit" class="button bg-blue-700">
              Lưu thay đổi
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/userauths/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link href="assets/images/favicon.png" rel="icon" type="image/png" />

    <!-- Basic Page Needs
        ================================================== -->
    <title>Open World</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="Socialite is - Professional A unique and beautiful collection of UI elements"
    />

    <!-- icons
    ================================================== -->
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}" />
    <!-- CSS 
    ================================================== -->
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="lg:flex max-w-5xl min-h-screen mx-auto p-6 py-10">
      <div class="flex flex-col items-center lg: lg:flex-row lg:space-x-10">
        <div class="lg:mb-12 flex-1 lg:text-left text-center">
          <img
            src="{% static 'assets/images/logo.png' %}"
            alt=""
            class="lg:mx-0 lg:w-52 mx-auto w-40"
          />
          <p
            class="font-medium lg:mx-0 md:text-2xl mt-6 mx-auto sm:w-3/4 text-xl"
          >
            Kết nối với thế giới cùng Open World
          </p>
        </div>
        <div class="lg:mt-0 lg:w-96 md:w-1/2 sm:w-2/3 mt-10 w-full">
          <!-- Form Errors -->
          {% if form.errors %}
          <div
            class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"
            role="alert"
          >
            <strong class="font-bold">{{form.errors}}</strong>
            <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
              <svg
                class="fill-current h-6 w-6 text-red-500"
                role="button"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
              >
                <title>Đóng</title>
                <path
                  d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"
                />
              </svg>
            </span>
          </div>
          {% endif %} {% if messages %} {% for message in messages %}
          <div
            class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative"
            role="alert"
          >
            <strong class="font-bold">{{message}}</strong>
            <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
              <svg
                class="fill-current h-6 w-6 text-red-500"
                role="button"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
              >
                <title>Đóng</title>
                <path
                  d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"
                />
              </svg>
            </span>
          </div>
          {% endfor %} {% endif %}

          <form
            class="p-6 space-y-4 relative bg-white shadow-lg rounded-lg"
            method="POST"
            action="{% url 'userauths:login' %}"
          >
            {% csrf_token %}
            <input
              type="email"
              name="email"
              placeholder="Email, Phone Number"
              class="with-border"
            />
            <input
              type="password"
              name="password"
              placeholder="Password"
              class="with-border"
            />
            <button
              type="submit"
              class="bg-blue-600 font-semibold p-3 rounded-md text-center text-white w-full"
            >
              Đăng nhập
            </button>
            <hr class="pb-3.5" />
            <div class="flex">
              <a
                href="#register"
                type="button"
                class="bg-green-600 hover:bg-green-500 hover:text-white font-semibold py-3 px-5 rounded-md text-center text-white mx-auto"
                uk-toggle
              >
                Tạo tài khoản mới
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- This is the modal -->
    <div id="register" uk-modal>
      <div
        class="uk-modal-dialog uk-modal-body rounded-xl shadow-2xl p-0 lg:w-5/12"
      >
        <button
          class="uk-modal-close-default p-3 bg-gray-100 rounded-full m-3"
          type="button"
          uk-close
        ></button>
        <div class="border-b px-7 py-5">
          <div class="lg:text-2xl text-xl font-semibold mb-1">Đăng ký</div>
          <div class="text-base text-gray-600">Nhanh và dễ dàng</div>
        </div>
        <form class="p-7 space-y-5" novalidate method="POST">
          {% csrf_token %} {{form.full_name}}

          <div class="grid lg:grid-cols-2 gap-3">
            <div>
              <label class=""> Tên người dùng </label>
              {{form.username}}
            </div>
            <div>
              <label class="">Email</label>
              {{form.email}}
            </div>
          </div>

          <div class="grid lg:grid-cols-2 gap-3">
            <div>
              <label class=""> Giới tính </label>
              {{form.gender}}
            </div>
            <div>
              <label class=""> SĐT </label>
              {{form.phone}}
            </div>
          </div>
          <div class="grid lg:grid-cols-2 gap-3">
            <div>
              <label class=""> Mật khẩu </label>
              {{form.password1}}
            </div>
            <div>
              <label class="">Xác nhận mật khẩu </label>
              {{form.password2}}
            </div>
          </div>
          <p class="text-xs text-gray-400 pt-3">
            Khi bạn nhấn vào Đăng Kí, bạn đã đồng ý với
            <a href="#" class="text-blue-500">Điều khoản</a>,
            <a href="#">Data Policy</a> và <a href="#">Cookies Policy</a> của
            chúng tôi.
          </p>
          <div class="flex">
            <button
              type="submit"
              class="bg-blue-600 font-semibold mx-auto px-10 py-3 rounded-md text-center text-white"
            >
              Xác nhận
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- Javascript
    ================================================== -->
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-select.min.js' %}"></script>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
  </body>
</html>